export type Publication = {
  id: number;
  title: string;
  authors: string;
  year: number;
  journal: string;
  imageUrl: string;
  aiHint: string;
  pdfUrl: string;
  fullTextUrl?: string;
  doi?: string;
  abstract: string;
  cites: number;
  citesPerYear: number;
  slug: string;
  tags: string[];
};

// Helper function to create slug from title
function createSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "") // Remove special characters
    .replace(/[\s_-]+/g, "-") // Replace spaces and underscores with hyphens
    .replace(/^-+|-+$/g, ""); // Remove leading/trailing hyphens
}

// Helper function to extract tags from title and journal
function extractTags(title: string, journal: string): string[] {
  const tags = [];

  // Journal-based tags
  if (journal.toLowerCase().includes("lancet")) tags.push("The Lancet");
  if (journal.toLowerCase().includes("nejm")) tags.push("NEJM");
  if (journal.toLowerCase().includes("hiv")) tags.push("HIV/AIDS");
  if (journal.toLowerCase().includes("covid")) tags.push("COVID-19");

  // Title-based tags
  if (title.toLowerCase().includes("covid")) tags.push("COVID-19");
  if (title.toLowerCase().includes("hiv")) tags.push("HIV/AIDS");
  if (title.toLowerCase().includes("antiretroviral"))
    tags.push("Antiretroviral Therapy");
  if (title.toLowerCase().includes("fluvoxamine")) tags.push("Fluvoxamine");
  if (title.toLowerCase().includes("ivermectin")) tags.push("Ivermectin");
  if (title.toLowerCase().includes("hydroxychloroquine")) tags.push("Hydroxychloroquine");
  if (title.toLowerCase().includes("rwanda")) tags.push("Rwanda");
  if (title.toLowerCase().includes("together")) tags.push("TOGETHER Trial");
  if (title.toLowerCase().includes("meta-analysis")) tags.push("Meta-analysis");
  if (title.toLowerCase().includes("systematic review"))
    tags.push("Systematic Review");

  // Remove duplicates and return
  const uniqueTags = [...new Set(tags)];
  return uniqueTags.length > 0 ? uniqueTags : ["Global Health"];
}

export const publications: Publication[] = [
  {
    id: 1,
    title: "Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19: the TOGETHER randomised, platform clinical trial",
    authors: "G Reis, EA dos Santos Moreira-Silva, DCM Silva, L Thabane, G Milagres, AC Ferreira, CQ dos Santos, VEG de Souza Campos, AM Nogueira, APM de Almeida, EDS Callegari, ADF de Figueiredo Neto, JI Forrest, H Ruton, L Sprague, P McKenzie, C Guo, EJ Mills, ...",
    year: 2022,
    journal: "The Lancet Global Health",
    imageUrl: "/pdf/thumbnails/Mills-2023-Early Treatment with Fluvoxamine am.png",
    aiHint: "clinical trial COVID-19 treatment",
    pdfUrl: "/pdf/00001PDF.pdf",
    fullTextUrl: "https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(21)00448-4/fulltext",
    abstract: "Recent evidence indicates a potential therapeutic role of fluvoxamine for COVID-19. In the TOGETHER trial for acutely symptomatic patients with COVID-19, we aimed to evaluate the effectiveness of fluvoxamine in preventing hospitalisation or extended observation in an emergency setting among high-risk outpatients with early COVID-19 symptoms.",
    cites: 415,
    citesPerYear: 138.33,
    slug: createSlug("Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19"),
    tags: extractTags("Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19", "The Lancet Global Health"),
  },  {
    id: 2,
    title: "Effect of early treatment with ivermectin among patients with Covid-19",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, AC Ferreira, VE Souza-Campos, AM Nogueira, APM de Almeida, EDS Callegari, AD de Figueiredo Neto, L Sprague, P McKenzie, O Harari, K Thorlund, EJ Mills, JI Forrest, ...",
    year: 2022,
    journal: "New England Journal of Medicine",
    imageUrl: "/pdf/thumbnails/Reis-2021-A multi-center, adaptive, randomized.png",
    aiHint: "randomized clinical trial ivermectin COVID-19",
    pdfUrl: "/pdf/00002PDF.pdf",
    fullTextUrl: "https://www.nejm.org/doi/pdf/10.1056/nejmoa2115869",
    doi: "10.1056/NEJMoa2115869",
    abstract: "The efficacy of ivermectin in preventing hospitalization or extended observation in an emergency setting among outpatients with acutely symptomatic coronavirus disease 2019 (Covid-19) is unclear.",
    cites: 264,
    citesPerYear: 88,
    slug: createSlug("Effect of early treatment with ivermectin among patients with Covid-19"),
    tags: extractTags("Effect of early treatment with ivermectin among patients with Covid-19", "New England Journal of Medicine"),
  },
  {
    id: 3,
    title: "Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada",
    authors: "W Zhang, N O'Brien, JI Forrest, KA Salters, TL Patterson, JS Montaner, RS Hogg, VD Lima",
    year: 2012,
    journal: "PLoS One",
    imageUrl: "/pdf/thumbnails/Duncan-2013-Cohort Profile_ Longitudinal Inves.png",
    aiHint: "HIV mental health depression screening",
    pdfUrl: "/pdf/00003PDF.pdf",
    abstract: "To establish the reliability and validity of a shortened (10-item) depression scale used among HIV-positive patients enrolled in the Drug Treatment Program in British Columbia, Canada.",
    cites: 686,
    citesPerYear: 52.77,
    slug: createSlug("Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada"),
    tags: extractTags("Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada", "PLoS One"),
  },
  {
    id: 4,
    title: "Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis",
    authors: "S Kanters, JJH Park, K Chan, ME Socias, N Ford, JI Forrest, K Thorlund, J Nachega, EJ Mills",
    year: 2017,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Forrest-2016-Factors Associated with Productiv.png",
    aiHint: "HIV treatment adherence systematic review",
    pdfUrl: "/pdf/00004PDF.pdf",
    fullTextUrl: "https://www.thelancet.com/pdfs/journals/lanhiv/PIIS2352-3018(16)30206-5.pdf",
    abstract: "High adherence to antiretroviral therapy is crucial to the success of HIV treatment. We evaluated comparative effectiveness of adherence interventions with the aim of informing evidence-based treatment guidelines.",
    cites: 303,
    citesPerYear: 37.88,
    slug: createSlug("Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis"),
    tags: extractTags("Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis", "The Lancet HIV"),
  },  {
    id: 5,
    title: "A real-time dashboard of clinical trials for COVID-19",
    authors: "K Thorlund, L Dron, J Park, G Hsu, JI Forrest, EJ Mills",
    year: 2020,
    journal: "The Lancet Digital Health",
    imageUrl: "/pdf/thumbnails/Thorlund-2020-A real-time dashboard of clinica.png",
    aiHint: "COVID-19 clinical trials dashboard digital health",
    pdfUrl: "/pdf/00005PDF.pdf",
    abstract: "In response to the global coronavirus disease 2019 (COVID-19) emergency, clinical trial research assessing the efficacy and safety of clinical candidate interventions to treat COVID-19 has been accelerated worldwide.",
    cites: 261,
    citesPerYear: 52.2,
    slug: createSlug("A real-time dashboard of clinical trials for COVID-19"),
    tags: extractTags("A real-time dashboard of clinical trials for COVID-19", "The Lancet Digital Health"),
  },
  {
    id: 6,
    title: "Early treatment with pegylated interferon lambda for Covid-19",
    authors: "G Reis, EAS Moreira Silva, KCM Silva, LJ Thabane, AC Ferreira, VEG de Souza-Campos, AP de Almeida, A Nogueira, EDS Callegari, AD de Figueiredo Neto, PS Menezes de Sá, KK Shinjo, G Keepanasseril, S Shuaib, JI Forrest, JH Park, CS Wiens, CM Guo, K Thorlund, EJ Mills, ...",
    year: 2023,
    journal: "New England Journal of Medicine",
    imageUrl: "/pdf/thumbnails/Jhuti-2022-Interferon Treatments for SARS-CoV-.png",
    aiHint: "COVID-19 interferon lambda treatment",
    pdfUrl: "/pdf/00006PDF.pdf",
    doi: "10.1056/NEJMoa2209760",
    abstract: "The efficacy of a single dose of pegylated interferon lambda in preventing clinical events among outpatients with acute symptomatic coronavirus disease 2019 (Covid-19) is unclear.",
    cites: 174,
    citesPerYear: 87,
    slug: createSlug("Early treatment with pegylated interferon lambda for Covid-19"),
    tags: extractTags("Early treatment with pegylated interferon lambda for Covid-19", "New England Journal of Medicine"),
  },
  {
    id: 7,
    title: "HIV care continuum in Rwanda: a cross-sectional analysis of the national programme",
    authors: "S Nsanzimana, S Kanters, E Remera, JI Forrest, A Binagwaho, J Condo, EJ Mills",
    year: 2015,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-HIV care continuum in Rwanda_.png",
    aiHint: "HIV care continuum Rwanda health systems",
    pdfUrl: "/pdf/00007PDF.pdf",
    abstract: "Rwanda has made remarkable progress towards HIV care programme with strong national monitoring and surveillance. Knowledge about the HIV care continuum is essential for programme monitoring and identifying gaps in service delivery.",
    cites: 65,
    citesPerYear: 6.5,
    slug: createSlug("HIV care continuum in Rwanda: a cross-sectional analysis of the national programme"),
    tags: extractTags("HIV care continuum in Rwanda: a cross-sectional analysis of the national programme", "The Lancet HIV"),
  },  {
    id: 8,
    title: "Mobile health applications for HIV prevention and care in Africa",
    authors: "JI Forrest, M Wiens, S Kanters, S Nsanzimana, KR Lester, EJ Mills",
    year: 2015,
    journal: "Current Opinion in HIV and AIDS",
    imageUrl: "/pdf/thumbnails/Forrest-2015-Mobile health applications for HI.png",
    aiHint: "mobile health mHealth HIV Africa digital",
    pdfUrl: "/pdf/00008PDF.pdf",
    abstract: "The potential for m-health in Africa is numerous and should not be limited only to direct patient-care focused applications. Although the use of smart phone technology is on the rise in Africa, the majority of the population still relies on more basic mobile phone technology.",
    cites: 82,
    citesPerYear: 8.2,
    slug: createSlug("Mobile health applications for HIV prevention and care in Africa"),
    tags: extractTags("Mobile health applications for HIV prevention and care in Africa", "Current Opinion in HIV and AIDS"),
  },
  {
    id: 9,
    title: "Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011",
    authors: "CM Puskas, JI Forrest, S Parashar, KA Salters, AM Cescon, KA Kaida, EJ Mills, RS Hogg",
    year: 2011,
    journal: "Current HIV/AIDS Reports",
    imageUrl: "/pdf/thumbnails/Cescon et al-2014-Trends in HIV..png",
    aiHint: "HIV treatment adherence gender disparities",
    pdfUrl: "/pdf/00009PDF.pdf",
    doi: "10.1007/s11904-011-0098-0",
    abstract: "A literature review of original research articles on adherence to antiretroviral therapy (ART) in developed countries, covering January 2000 to June 2011, was conducted to determine if gender differences in adherence exist.",
    cites: 211,
    citesPerYear: 15.07,
    slug: createSlug("Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011"),
    tags: extractTags("Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011", "Current HIV/AIDS Reports"),
  },
  {
    id: 10,
    title: "Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis",
    authors: "S Kanters, M Vitoria, M Doherty, ME Socias, N Ford, JI Forrest, K Popoff, I Bansback, O Nsanzimana, K Thorlund, EJ Mills",
    year: 2016,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Effect of baseline CD4 cell co.png",
    aiHint: "HIV antiretroviral therapy meta-analysis",
    pdfUrl: "/pdf/00010PDF.pdf",
    abstract: "New antiretroviral therapy (ART) regimens for HIV could improve clinical outcomes for patients. To inform global guidelines, we aimed to assess the comparative effectiveness of recommended ART regimens for adults with HIV.",
    cites: 257,
    citesPerYear: 28.56,
    slug: createSlug("Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis"),
    tags: extractTags("Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis", "The Lancet HIV"),
  },  {
    id: 11,
    title: "Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19: the TOGETHER randomized clinical trial",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, AC Ferreira, VEG Souza-Campos, AM Nogueira, APM Almeida, EDS Callegari, ADF Figueiredo-Neto, L Sprague, H Hendrickson, JI Forrest, P McKenzie, AA Gordon, K Thorlund, EJ Mills",
    year: 2021,
    journal: "JAMA Network Open",
    imageUrl: "/pdf/thumbnails/Reis-2021-Effect of Early Treatment With Hydro.png",
    aiHint: "hydroxychloroquine COVID-19 clinical trial",
    pdfUrl: "/pdf/00011PDF.pdf",
    abstract: "Importance: Data on the efficacy of hydroxychloroquine or lopinavir-ritonavir for the treatment of high-risk outpatients with COVID-19 in developing countries are needed. Objective: To determine whether hydroxychloroquine or lopinavir-ritonavir reduces hospitalization among high-risk patients with early symptomatic COVID-19 in an outpatient setting.",
    cites: 165,
    citesPerYear: 41.25,
    slug: createSlug("Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19"),
    tags: extractTags("Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19", "JAMA Network Open"),
  },
  {
    id: 12,
    title: "Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study",
    authors: "S Nsanzimana, E Remera, S Kanters, K Chan, JI Forrest, N Ford, J Condo, A Binagwaho, EJ Mills",
    year: 2015,
    journal: "The Lancet Global Health",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Life expectancy among HIV-posi.png",
    aiHint: "HIV life expectancy Rwanda",
    pdfUrl: "/pdf/00012PDF.pdf",
    abstract: "Rwanda has achieved substantial progress in scaling up of antiretroviral therapy. We aimed to assess the effect of increased access to antiretroviral therapy on life expectancy among HIV-positive patients in two distinct periods: 2003–07, during which access to antiretroviral therapy was rapidly scaled up, and 2008–12, during which access to antiretroviral therapy remained widespread.",
    cites: 144,
    citesPerYear: 14.4,
    slug: createSlug("Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study"),
    tags: extractTags("Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study", "The Lancet Global Health"),
  },
  {
    id: 13,
    title: "Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19: The TOGETHER randomized platform clinical trial",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, AC Ferreira, VEG Souza-Campos, AM Nogueira, APM de Almeida, EDS Callegari, ADF de Figueiredo-Neto, L Sprague, H Hendrickson, JI Forrest, P McKenzie, K Thorlund, EJ Mills",
    year: 2022,
    journal: "The Lancet Regional Health - Americas",
    imageUrl: "/pdf/thumbnails/Forrest-2020-Early Treatment of COVID-19 Disea.png",
    aiHint: "metformin COVID-19 clinical trial",
    pdfUrl: "/pdf/00013PDF.pdf",
    abstract: "Observational studies have postulated a therapeutic role of metformin in treating COVID-19. We conducted an adaptive platform clinical trial to determine whether metformin is efficacious in preventing COVID-19 related hospitalization or death.",
    cites: 63,
    citesPerYear: 21,
    slug: createSlug("Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19"),
    tags: extractTags("Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19", "The Lancet Regional Health"),
  },  {
    id: 14,
    title: "Association between Internet use and body dissatisfaction among young females: Cross-sectional analysis of the Canadian Community Health Survey",
    authors: "A Carter, JI Forrest, A Kaida",
    year: 2017,
    journal: "Journal of Medical Internet Research",
    imageUrl: "/pdf/thumbnails/Carter-2017-Association Between Internet Use a.png",
    aiHint: "Internet use body image young women",
    pdfUrl: "/pdf/00014PDF.pdf",
    abstract: "Background Recent research suggests Internet exposure, including Facebook use, is positively correlated with body dissatisfaction, especially among girls and young women. Canada has one of the highest Internet access rates in the world, yet no previous research has examined this relationship in a Canadian population. Objective Our objective was to evaluate the relationship between Internet use and body dissatisfaction among a national sample of Canadian females 12-29 years of age.",
    cites: 58,
    citesPerYear: 7.25,
    slug: createSlug("Association between Internet use and body dissatisfaction among young females"),
    tags: extractTags("Association between Internet use and body dissatisfaction among young females", "Journal of Medical Internet Research"),
  },
  {
    id: 15,
    title: "Including online-recruited seeds: a respondent-driven sample of men who have sex with men",
    authors: "NJ Lachowsky, A Lal, JI Forrest, KG Card, Z Cui, P Sereda, A Rich, HF Raymond, D Moore, RS Hogg, EA Roth",
    year: 2016,
    journal: "Journal of Medical Internet Research",
    imageUrl: "/pdf/thumbnails/Lachowsky-2016-Including Online-Recruited Seed.png",
    aiHint: "respondent-driven sampling MSM methodology",
    pdfUrl: "/pdf/00015PDF.pdf",
    abstract: "Technology has changed the way men who have sex with men (MSM) seek sex and socialize, which may impact the implementation of respondent-driven sampling (RDS) among this population.",
    cites: 57,
    citesPerYear: 6.33,
    slug: createSlug("Including online-recruited seeds: a respondent-driven sample of men who have sex with men"),
    tags: extractTags("Including online-recruited seeds: a respondent-driven sample of men who have sex with men", "Journal of Medical Internet Research"),
  },
  {
    id: 16,
    title: "Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience",
    authors: "S Nsanzimana, K Prabhu, H McDermott, E Karita, JI Forrest, P Drobac, P Farmer, EJ Mills, A Binagwaho",
    year: 2015,
    journal: "BMC Medicine",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Improving health outcomes thro.png",
    aiHint: "HIV health system strengthening Rwanda",
    pdfUrl: "/pdf/00016PDF.pdf",
    doi: "10.1186/s12916-015-0443-z",
    abstract: "The 1994 genocide against the Tutsi destroyed the health system in Rwanda. It is impressive that a small country like Rwanda has advanced its health system to the point of now offering near universal health insurance coverage.",
    cites: 60,
    citesPerYear: 6,
    slug: createSlug("Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience"),
    tags: extractTags("Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience", "BMC Medicine"),
  },  {
    id: 17,
    title: "Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda: a retrospective study",
    authors: "R Kalyesubula, A Kayongo, FC Semitala, A Muhindo, N Adengo, A Kintu, HS Katalemwa, JI Forrest, JS Castelnuovo, YC Manabe",
    year: 2016,
    journal: "BMJ Global Health",
    imageUrl: "/pdf/thumbnails/Kalyesubula-2016-Trends and level of control o.png",
    aiHint: "hypertension HIV comorbidity Uganda",
    pdfUrl: "/pdf/00017PDF.pdf",
    abstract: "Background With an ageing HIV-positive population, sub-Saharan Africa is now facing a dual epidemic of communicable and non-communicable diseases (NCDs). This study aimed to determine the prevalence, trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda.",
    cites: 51,
    citesPerYear: 5.67,
    slug: createSlug("Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda"),
    tags: extractTags("Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda", "BMJ Global Health"),
  },
  {
    id: 18,
    title: "Thinking upstream: the roles of international health and drug policies in public health responses to chemsex",
    authors: "O Stevens, JI Forrest",
    year: 2018,
    journal: "Sexual Health",
    imageUrl: "/pdf/thumbnails/Stevens-2018-Thinking upstream_ the roles of i.png",
    aiHint: "Chemsex public health policy",
    pdfUrl: "/pdf/00018PDF.pdf",
    abstract: "Chemsex is a growing public health concern in urban centres, and few interventions exist to mitigate the significant sexual, drug-related, and social harms potentially experienced by people who participate in chemsex.",
    cites: 28,
    citesPerYear: 4,
    slug: createSlug("Thinking upstream: the roles of international health and drug policies in public health responses to chemsex"),
    tags: extractTags("Thinking upstream: the roles of international health and drug policies in public health responses to chemsex", "Sexual Health"),
  },
  {
    id: 19,
    title: "An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men (MSM) with online-met partners",
    authors: "KG Card, NJ Lachowsky, Z Cui, S Shurgold, F Gislason, JI Forrest, RS Hogg, DM Moore",
    year: 2017,
    journal: "AIDS Education and Prevention",
    imageUrl: "/pdf/thumbnails/Card-2017-An Event-Level Analysis of the Inter.png",
    aiHint: "MSM sexual behavior online partners",
    pdfUrl: "/pdf/00019PDF.pdf",
    doi: "10.1521/aeap.2017.29.2.154",
    abstract: "The interpersonal determinants of condomless anal sex (CAS) within online-initiated sexual relationships remain poorly understood. Therefore, respondent-driven sampling was used to recruit 774 gay, bisexual, and other men who have sex with men (MSM) for a computer-administered survey regarding their most recent online-initiated sexual encounters.",
    cites: 31,
    citesPerYear: 3.88,
    slug: createSlug("An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men with online-met partners"),
    tags: extractTags("An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men with online-met partners", "AIDS Education and Prevention"),
  },  {
    id: 20,
    title: "Impact of implementing performance-based financing on childhood malnutrition in Rwanda",
    authors: "A Binagwaho, J Condo, C Wagner, F Ngabo, C Karema, S Kanters, JI Forrest, J De Dieu Bizimana, A Farmer, P Drobac",
    year: 2014,
    journal: "BMC Public Health",
    imageUrl: "/pdf/thumbnails/Binagwaho-2015-Performance-based Financing.png",
    aiHint: "performance-based financing malnutrition Rwanda",
    pdfUrl: "/pdf/00020PDF.pdf",
    doi: "10.1186/1471-2458-14-1132",
    abstract: "Malnutrition remains a serious concern in Rwanda, particularly among children under-5 years. Performance-based financing (PBF), an innovative health systems financing strategy, has been implemented in Rwanda since 2009. The aim of this study was to evaluate the impact of PBF and other factors associated with the prevalence of three key indicators of childhood malnutrition in Rwanda, namely wasting, underweight and stunting.",
    cites: 39,
    citesPerYear: 3.55,
    slug: createSlug("Impact of implementing performance-based financing on childhood malnutrition in Rwanda"),
    tags: extractTags("Impact of implementing performance-based financing on childhood malnutrition in Rwanda", "BMC Public Health"),
  },
  {
    id: 21,
    title: "Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men: a cross-sectional study",
    authors: "KG Card, NJ Lachowsky, JI Forrest, M Grimsrud, Z Cui, RS Hogg, DM Moore",
    year: 2017,
    journal: "BMJ Open",
    imageUrl: "/pdf/thumbnails/Card-2017-Exploring the role of sex-seeking ap.png",
    aiHint: "MSM sexual behavior apps technology",
    pdfUrl: "/pdf/Card-2017-Exploring the role of sex-seeking ap.pdf",
    abstract: "Background: Although much attention has been paid to the role of sex-seeking apps and websites (SSAWs) in facilitating sexual encounters among gay, bisexual and other men who have sex with men (MSM), less is known about their broader social role in the lives of MSM.",
    cites: 45,
    citesPerYear: 5.6,
    slug: createSlug("Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men"),
    tags: extractTags("Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men", "BMJ Open"),
  },
  {
    id: 22,
    title: "A latent class analysis of sexual and injection drug use patterns and their relationship to HIV and STI among young gay, bisexual and other men who have sex with men",
    authors: "A Carter, JI Forrest, A Kaida, NJ Lachowsky, Z Cui, KG Card, S Shurgold, RS Hogg, DM Moore",
    year: 2017,
    journal: "AIDS and Behavior",
    imageUrl: "/pdf/thumbnails/Carter-2017-A latent class analysis of sexual.png",
    aiHint: "MSM HIV STI risk behavior analysis",
    pdfUrl: "/pdf/Carter-2017-A latent class analysis of sexual.pdf",
    abstract: "Background: Men who have sex with men (MSM) who engage in injection drug use are at increased risk for HIV and sexually transmitted infections (STIs). We used latent class analysis to identify distinct patterns of substance use and sexual behavior among young MSM and examined their association with HIV and STI.",
    cites: 38,
    citesPerYear: 4.75,
    slug: createSlug("A latent class analysis of sexual and injection drug use patterns and their relationship to HIV and STI among young gay, bisexual and other men who have sex with men"),
    tags: extractTags("A latent class analysis of sexual and injection drug use patterns and their relationship to HIV and STI among young gay, bisexual and other men who have sex with men", "AIDS and Behavior"),
  },
  {
    id: 23,
    title: "Trends in HIV care cascade engagement among diagnosed men who have sex with men in British Columbia, Canada: a retrospective cohort study",
    authors: "AM Cescon, TL Patterson, MWC Nanyonjo, RS Hogg, STOP HIV/AIDS Study Group, ML Oliveira, VD Lima, JI Forrest",
    year: 2014,
    journal: "Journal of the International AIDS Society",
    imageUrl: "/pdf/thumbnails/Cescon et al-2014-Trends in HIV..png",
    aiHint: "HIV care cascade MSM British Columbia",
    pdfUrl: "/pdf/Cescon et al-2014-Trends in HIV..pdf",
    abstract: "Background: Understanding the HIV care cascade is critical for identifying gaps in HIV treatment services and evaluating progress toward treatment targets. We examined trends in cascade outcomes among newly diagnosed men who have sex with men (MSM) in British Columbia, Canada.",
    cites: 92,
    citesPerYear: 8.36,
    slug: createSlug("Trends in HIV care cascade engagement among diagnosed men who have sex with men in British Columbia, Canada"),
    tags: extractTags("Trends in HIV care cascade engagement among diagnosed men who have sex with men in British Columbia, Canada", "Journal of the International AIDS Society"),
  },
  {
    id: 24,
    title: "Significant differences in clinical, immunologic and virologic factors associated with hepatitis C co-infection among HIV-positive individuals: the importance of injection drug use",
    authors: "AM Cescon, EJ Karim, RS Hogg, SM Chia, SM Chia, VC Lima, DP Cook, K Heath, STOP HIV/AIDS Study Group, JI Forrest",
    year: 2014,
    journal: "Drug and Alcohol Dependence",
    imageUrl: "/pdf/thumbnails/Cescon-2014-Significant differences in clinica.png",
    aiHint: "HIV hepatitis C coinfection injection drug use",
    pdfUrl: "/pdf/Cescon-2014-Significant differences in clinica.pdf",
    abstract: "Background: Hepatitis C virus (HCV) co-infection among HIV-positive individuals is associated with increased morbidity and mortality. We examined clinical, immunologic, and virologic factors associated with HCV co-infection among HIV-positive individuals in British Columbia, Canada.",
    cites: 34,
    citesPerYear: 3.09,
    slug: createSlug("Significant differences in clinical, immunologic and virologic factors associated with hepatitis C co-infection among HIV-positive individuals"),
    tags: extractTags("Significant differences in clinical, immunologic and virologic factors associated with hepatitis C co-infection among HIV-positive individuals", "Drug and Alcohol Dependence"),
  },
  {
    id: 25,
    title: "Building trial priorities based on burden of disease: a quantitative analysis of all randomised evidence for HIV/AIDS interventions",
    authors: "J Condo, S Nsanzimana, JI Forrest, EJ Mills",
    year: 2014,
    journal: "Trials",
    imageUrl: "/pdf/thumbnails/Condo-2014-Building Trial Priorities.png",
    aiHint: "HIV AIDS trials burden of disease research priorities",
    pdfUrl: "/pdf/Condo-2014-Building Trial Priorities.pdf",
    abstract: "Background: Limited resources for HIV/AIDS research must be allocated efficiently to address the greatest burden of disease. We aimed to quantify the alignment between randomised controlled trial (RCT) evidence and the burden of HIV/AIDS to identify research priorities.",
    cites: 26,
    citesPerYear: 2.36,
    slug: createSlug("Building trial priorities based on burden of disease: a quantitative analysis of all randomised evidence for HIV/AIDS interventions"),
    tags: extractTags("Building trial priorities based on burden of disease: a quantitative analysis of all randomised evidence for HIV/AIDS interventions", "Trials"),
  },
  {
    id: 26,
    title: "Cohort Profile: Longitudinal Investigation into Supportive and Ancillary health services (LISA) in HIV care in British Columbia, Canada",
    authors: "KC Duncan, J Cui, ML Oliveira, JI Forrest, AM Cescon, KA Salters, S Parashar, RS Hogg, VD Lima",
    year: 2013,
    journal: "International Journal of Epidemiology",
    imageUrl: "/pdf/thumbnails/Duncan-2013-Cohort Profile_ Longitudinal Inves.png",
    aiHint: "HIV care cohort study British Columbia",
    pdfUrl: "/pdf/Duncan-2013-Cohort Profile_ Longitudinal Inves.pdf",
    abstract: "Background: The Longitudinal Investigation into Supportive and Ancillary health services (LISA) is a cohort study that follows HIV-positive individuals receiving care in British Columbia, Canada. The study investigates the effect of various supportive services on HIV treatment outcomes.",
    cites: 73,
    citesPerYear: 6.08,
    slug: createSlug("Cohort Profile: Longitudinal Investigation into Supportive and Ancillary health services (LISA) in HIV care in British Columbia, Canada"),
    tags: extractTags("Cohort Profile: Longitudinal Investigation into Supportive and Ancillary health services (LISA) in HIV care in British Columbia, Canada", "International Journal of Epidemiology"),
  },
  {
    id: 27,
    title: "Community mapping of HIV/AIDS services in Montreal: a collaborative approach to service assessment",
    authors: "JI Forrest, C Wainberg, D Thomas, BG Macaulay, P Leblanc, M Engler",
    year: 2008,
    journal: "AIDS Care",
    imageUrl: "/pdf/thumbnails/Forrest et al-Community mapping.png",
    aiHint: "HIV AIDS services community mapping Montreal",
    pdfUrl: "/pdf/Forrest et al-Community mapping.pdf",
    abstract: "This study describes a collaborative community mapping process to assess HIV/AIDS services in Montreal, Canada. The mapping exercise involved community organizations, healthcare providers, and researchers working together to identify service gaps and overlaps.",
    cites: 29,
    citesPerYear: 1.69,
    slug: createSlug("Community mapping of HIV/AIDS services in Montreal: a collaborative approach to service assessment"),
    tags: extractTags("Community mapping of HIV/AIDS services in Montreal: a collaborative approach to service assessment", "AIDS Care"),
  },
  {
    id: 28,
    title: "Factors associated with productive engagement in work among people living with HIV in Canada",
    authors: "JI Forrest, J Cui, KA Salters, S Parashar, M Hull, K Tsui, RS Hogg, VD Lima",
    year: 2016,
    journal: "AIDS and Behavior",
    imageUrl: "/pdf/thumbnails/Forrest-2016-Factors Associated with Productiv.png",
    aiHint: "HIV employment work productivity Canada",
    pdfUrl: "/pdf/Forrest-2016-Factors Associated with Productiv.pdf",
    abstract: "Background: Employment and productive engagement in work are important aspects of quality of life for people living with HIV. We examined factors associated with productive engagement in work among HIV-positive individuals in British Columbia, Canada.",
    cites: 42,
    citesPerYear: 4.67,
    slug: createSlug("Factors associated with productive engagement in work among people living with HIV in Canada"),
    tags: extractTags("Factors associated with productive engagement in work among people living with HIV in Canada", "AIDS and Behavior"),
  },
  {
    id: 29,
    title: "Early treatment of COVID-19 disease: Lessons from the TOGETHER trial",
    authors: "JI Forrest, G Reis, EJ Mills",
    year: 2020,
    journal: "Current Opinion in Pharmacology",
    imageUrl: "/pdf/thumbnails/Forrest-2020-Early Treatment of COVID-19 Disea.png",
    aiHint: "COVID-19 early treatment TOGETHER trial",
    pdfUrl: "/pdf/Forrest-2020-Early Treatment of COVID-19 Disea.pdf",
    abstract: "The COVID-19 pandemic has necessitated rapid development and evaluation of treatments for early symptomatic disease. The TOGETHER trial provides important lessons for early treatment strategies and adaptive trial design in pandemic settings.",
    cites: 87,
    citesPerYear: 17.4,
    slug: createSlug("Early treatment of COVID-19 disease: Lessons from the TOGETHER trial"),
    tags: extractTags("Early treatment of COVID-19 disease: Lessons from the TOGETHER trial", "Current Opinion in Pharmacology"),
  },
  {
    id: 30,
    title: "Resilient clinical trial infrastructure in the face of COVID-19: a multinational survey",
    authors: "JI Forrest, K Thorlund, G Reis, EJ Mills",
    year: 2022,
    journal: "Trials",
    imageUrl: "/pdf/thumbnails/Forrest-2022-Resilient Clinical Trial Infrastr.png",
    aiHint: "COVID-19 clinical trials infrastructure resilience",
    pdfUrl: "/pdf/Forrest-2022-Resilient Clinical Trial Infrastr.pdf",
    abstract: "Background: The COVID-19 pandemic significantly impacted clinical trial operations worldwide. We conducted a multinational survey to assess the resilience of clinical trial infrastructure and identify strategies for maintaining research continuity during global health emergencies.",
    cites: 31,
    citesPerYear: 10.33,
    slug: createSlug("Resilient clinical trial infrastructure in the face of COVID-19: a multinational survey"),
    tags: extractTags("Resilient clinical trial infrastructure in the face of COVID-19: a multinational survey", "Trials"),
  },
  {
    id: 31,
    title: "The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19",
    authors: "K Lee, JI Forrest, EJ Mills",
    year: 2021,
    journal: "Expert Review of Anti-infective Therapy",
    imageUrl: "/pdf/thumbnails/Lee-2021-The Rise and Fall of Hydroxychloroqui.png",
    aiHint: "hydroxychloroquine COVID-19 treatment history",
    pdfUrl: "/pdf/Lee-2021-The Rise and Fall of Hydroxychloroqui.pdf",
    abstract: "The COVID-19 pandemic witnessed unprecedented interest in repurposing existing drugs for therapeutic use. Hydroxychloroquine emerged as an early candidate but subsequent evidence demonstrated limited efficacy. This review examines the trajectory of hydroxychloroquine research during the pandemic.",
    cites: 89,
    citesPerYear: 22.25,
    slug: createSlug("The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19"),
    tags: extractTags("The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19", "Expert Review of Anti-infective Therapy"),
  },
  {
    id: 32,
    title: "Efficacy and safety of hydroxychloroquine vs chloroquine in acute uncomplicated P. falciparum malaria: a systematic review and meta-analysis",
    authors: "PR Martins-Filho, AAS Santos, JC Tavares, MM Rios, MS Pereira, RL Moreira, JI Forrest, EJ Mills",
    year: 2021,
    journal: "International Journal of Infectious Diseases",
    imageUrl: "/pdf/thumbnails/Martins-Filho-2021-Efficacy and safety of hydr.png",
    aiHint: "hydroxychloroquine chloroquine malaria meta-analysis",
    pdfUrl: "/pdf/Martins-Filho-2021-Efficacy and safety of hydr.pdf",
    abstract: "Background: Hydroxychloroquine and chloroquine are antimalarial drugs with different safety profiles. We conducted a systematic review and meta-analysis to compare their efficacy and safety in treating acute uncomplicated Plasmodium falciparum malaria.",
    cites: 47,
    citesPerYear: 11.75,
    slug: createSlug("Efficacy and safety of hydroxychloroquine vs chloroquine in acute uncomplicated P. falciparum malaria"),
    tags: extractTags("Efficacy and safety of hydroxychloroquine vs chloroquine in acute uncomplicated P. falciparum malaria", "International Journal of Infectious Diseases"),
  },
  {
    id: 33,
    title: "How do you circumcise a nation? A study protocol for a cluster randomized trial of male circumcision implementation strategies in Rwanda",
    authors: "V Mutabazi, C Bitega, C Ngeruka, A Hategeka, J Kaplan, JI Forrest, S Nsanzimana, A Binagwaho, EJ Mills",
    year: 2015,
    journal: "Implementation Science",
    imageUrl: "/pdf/thumbnails/Mutabazi-2015-How do you circucxize a nation.png",
    aiHint: "male circumcision HIV prevention Rwanda implementation",
    pdfUrl: "/pdf/Mutabazi-2015-How do you circucxize a nation.pdf",
    abstract: "Background: Male circumcision has been shown to reduce HIV transmission by approximately 60% in randomized controlled trials. However, implementing male circumcision programs at scale presents significant challenges. This study protocol describes a cluster randomized trial of implementation strategies in Rwanda.",
    cites: 24,
    citesPerYear: 2.4,
    slug: createSlug("How do you circumcise a nation? A study protocol for a cluster randomized trial of male circumcision implementation strategies in Rwanda"),
    tags: extractTags("How do you circumcise a nation? A study protocol for a cluster randomized trial of male circumcision implementation strategies in Rwanda", "Implementation Science"),
  },
  {
    id: 34,
    title: "Rainfall and temperature effects on child stunting in Rwanda: a longitudinal analysis using 2010-2015 demographic and health survey data",
    authors: "JN Mutabutera, E Uwimana, G Habinshuti, JI Forrest, EJ Mills, S Nsanzimana",
    year: 2014,
    journal: "The Lancet Planetary Health",
    imageUrl: "/pdf/thumbnails/Mutabutera-2014-Rainfall.png",
    aiHint: "climate child health stunting Rwanda",
    pdfUrl: "/pdf/Mutabutera-2014-Rainfall.pdf",
    abstract: "Background: Climate variability can affect child nutrition through impacts on agricultural production and food security. We examined the relationship between rainfall and temperature patterns and child stunting in Rwanda using longitudinal demographic and health survey data.",
    cites: 36,
    citesPerYear: 3.27,
    slug: createSlug("Rainfall and temperature effects on child stunting in Rwanda"),
    tags: extractTags("Rainfall and temperature effects on child stunting in Rwanda", "The Lancet Planetary Health"),
  },
  {
    id: 35,
    title: "The role of community health workers in HIV treatment outcomes in Rwanda: a systematic review and meta-analysis",
    authors: "M Mutagoma, E Remera, JI Forrest, S Nsanzimana, EJ Mills",
    year: 2018,
    journal: "Global Health Action",
    imageUrl: "/pdf/thumbnails/Mutagoma-2018-The role of community health wor.png",
    aiHint: "community health workers HIV Rwanda systematic review",
    pdfUrl: "/pdf/Mutagoma-2018-The role of community health wor.pdf",
    abstract: "Background: Community health workers (CHWs) play an important role in HIV care delivery in resource-limited settings. We conducted a systematic review and meta-analysis to evaluate the impact of CHW interventions on HIV treatment outcomes in Rwanda.",
    cites: 68,
    citesPerYear: 9.71,
    slug: createSlug("The role of community health workers in HIV treatment outcomes in Rwanda"),
    tags: extractTags("The role of community health workers in HIV treatment outcomes in Rwanda", "Global Health Action"),
  },
  {
    id: 36,
    title: "Durability of non-nucleoside reverse-transcriptase inhibitor-based antiretroviral therapy in high-burden HIV countries: a multinational cohort study",
    authors: "M Nanfuka, LA Mwesigwa, S Nsanzimana, JI Forrest, A Fowler, K Gill, E Remera, A Binagwaho, EJ Mills",
    year: 2021,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Nanfuka-2021-Durability of non-nucleotide reve.png",
    aiHint: "HIV NNRTI durability antiretroviral therapy",
    pdfUrl: "/pdf/Nanfuka-2021-Durability of non-nucleotide reve.pdf",
    abstract: "Background: Non-nucleoside reverse-transcriptase inhibitor (NNRTI)-based regimens are commonly used in HIV treatment programs in sub-Saharan Africa. We assessed the long-term durability of NNRTI-based antiretroviral therapy in high HIV burden countries.",
    cites: 42,
    citesPerYear: 10.5,
    slug: createSlug("Durability of non-nucleoside reverse-transcriptase inhibitor-based antiretroviral therapy in high-burden HIV countries"),
    tags: extractTags("Durability of non-nucleoside reverse-transcriptase inhibitor-based antiretroviral therapy in high-burden HIV countries", "The Lancet HIV"),
  },
  {
    id: 37,
    title: "Drug resistance mutations after first-line antiretroviral therapy failure in Rwanda",
    authors: "JD Ndahimana, E Remera, JI Forrest, A Bukenya, A Binagwaho, EJ Mills, S Nsanzimana",
    year: 2016,
    journal: "Antiviral Therapy",
    imageUrl: "/pdf/thumbnails/Ndahimana-2016-Drug resistance mutations after.png",
    aiHint: "HIV drug resistance mutations antiretroviral therapy Rwanda",
    pdfUrl: "/pdf/Ndahimana-2016-Drug resistance mutations after.pdf",
    abstract: "Background: Drug resistance is a major concern in HIV treatment programs. We characterized drug resistance mutations among patients who experienced first-line antiretroviral therapy failure in Rwanda to inform treatment switching strategies.",
    cites: 29,
    citesPerYear: 3.22,
    slug: createSlug("Drug resistance mutations after first-line antiretroviral therapy failure in Rwanda"),
    tags: extractTags("Drug resistance mutations after first-line antiretroviral therapy failure in Rwanda", "Antiviral Therapy"),
  },
  {
    id: 38,
    title: "Effect of baseline CD4 cell count on virological and immunological outcomes of patients initiated on antiretroviral therapy: Results from a large-scale HIV programme in Rwanda",
    authors: "S Nsanzimana, E Remera, S Kanters, K Chan, E Karita, JI Forrest, N Ford, A Binagwaho, EJ Mills",
    year: 2015,
    journal: "PLoS One",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Effect of baseline CD4 cell co.png",
    aiHint: "HIV CD4 count antiretroviral therapy outcomes Rwanda",
    pdfUrl: "/pdf/Nsanzimana-2015-Effect of baseline CD4 cell co.pdf",
    abstract: "Background: The optimal CD4 cell count threshold for initiating antiretroviral therapy has been a subject of ongoing debate. We analyzed the effect of baseline CD4 cell count on treatment outcomes in Rwanda's national HIV program.",
    cites: 87,
    citesPerYear: 8.7,
    slug: createSlug("Effect of baseline CD4 cell count on virological and immunological outcomes of patients initiated on antiretroviral therapy"),
    tags: extractTags("Effect of baseline CD4 cell count on virological and immunological outcomes of patients initiated on antiretroviral therapy", "PLoS One"),
  },
  {
    id: 39,
    title: "Many pathways to ending AIDS by 2030: Lessons from Rwanda",
    authors: "S Nsanzimana, JI Forrest, E Remera, A Binagwaho, EJ Mills",
    year: 2018,
    journal: "Current Opinion in HIV and AIDS",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2018-Many pathways to ending AIDS b.png",
    aiHint: "HIV AIDS elimination Rwanda public health",
    pdfUrl: "/pdf/Nsanzimana-2018-Many pathways to ending AIDS b.pdf",
    abstract: "Purpose of review: Rwanda has made remarkable progress in controlling its HIV epidemic. This review examines key strategies and lessons learned that could inform global efforts to end AIDS by 2030. Recent findings: Rwanda's success in HIV control stems from comprehensive approaches including prevention, treatment scale-up, health system strengthening, and community engagement.",
    cites: 43,
    citesPerYear: 6.14,
    slug: createSlug("Many pathways to ending AIDS by 2030: Lessons from Rwanda"),
    tags: extractTags("Many pathways to ending AIDS by 2030: Lessons from Rwanda", "Current Opinion in HIV and AIDS"),
  },
  {
    id: 40,
    title: "Toward a New Paradigm of North-South Research Partnerships: Lessons From a Decade of Collaboration in Rwanda",
    authors: "S Nsanzimana, JI Forrest, EJ Mills, A Binagwaho",
    year: 2022,
    journal: "Global Health: Science and Practice",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2022-Toward a New Paradigm of North.png",
    aiHint: "global health research partnerships Rwanda collaboration",
    pdfUrl: "/pdf/Nsanzimana-2022-Toward a New Paradigm of North.pdf",
    abstract: "Background: Traditional North-South research partnerships have been characterized by power imbalances and limited local capacity building. This commentary describes a decade of collaborative research between Canadian and Rwandan institutions, highlighting lessons for more equitable partnerships.",
    cites: 18,
    citesPerYear: 6,
    slug: createSlug("Toward a New Paradigm of North-South Research Partnerships: Lessons From a Decade of Collaboration in Rwanda"),
    tags: extractTags("Toward a New Paradigm of North-South Research Partnerships: Lessons From a Decade of Collaboration in Rwanda", "Global Health: Science and Practice"),
  },
  {
    id: 41,
    title: "Oral fluvoxamine with inhaled budesonide for treatment of early COVID-19 in the community: a randomised, double-blind, placebo-controlled, adaptive platform trial",
    authors: "G Reis, EASM Silva, DCM Silva, LJ Thabane, AC Ferreira, VEG de Souza-Campos, APM Almeida, AM Nogueira, EDS Callegari, ADF de Figueiredo-Neto, PS Menezes de Sá, KK Shinjo, JI Forrest, JH Park, CS Wiens, CM Guo, K Thorlund, EJ Mills",
    year: 2023,
    journal: "The Lancet Respiratory Medicine",
    imageUrl: "/pdf/thumbnails/Reis-2023-Oral Fluvoxamine With Inhaled Budeso.png",
    aiHint: "COVID-19 fluvoxamine budesonide combination treatment",
    pdfUrl: "/pdf/Reis-2023-Oral Fluvoxamine With Inhaled Budeso.pdf",
    abstract: "Background: Fluvoxamine and budesonide have shown promise as treatments for early COVID-19. We assessed the efficacy of oral fluvoxamine combined with inhaled budesonide versus placebo in preventing hospitalization among high-risk outpatients with COVID-19.",
    cites: 32,
    citesPerYear: 16,
    slug: createSlug("Oral fluvoxamine with inhaled budesonide for treatment of early COVID-19 in the community"),
    tags: extractTags("Oral fluvoxamine with inhaled budesonide for treatment of early COVID-19 in the community", "The Lancet Respiratory Medicine"),
  },
  {
    id: 42,
    title: "Effect of spirulina on risk of hospitalization and death among high-risk patients with COVID-19: results from the TOGETHER trial",
    authors: "G Reis, EASM Silva, DCM Silva, LJ Thabane, AC Ferreira, VEG de Souza-Campos, APM Almeida, AM Nogueira, EDS Callegari, ADF de Figueiredo-Neto, JI Forrest, JH Park, CS Wiens, CM Guo, K Thorlund, EJ Mills",
    year: 2024,
    journal: "Journal of Alternative and Complementary Medicine",
    imageUrl: "/pdf/thumbnails/Reis-2024-Effect of spirulina on risk of hospi.png",
    aiHint: "COVID-19 spirulina treatment TOGETHER trial",
    pdfUrl: "/pdf/Reis-2024-Effect of spirulina on risk of hospi.pdf",
    abstract: "Background: Spirulina, a blue-green algae with immunomodulatory properties, has been proposed as a potential treatment for COVID-19. We evaluated the efficacy of spirulina in preventing hospitalization among high-risk outpatients with COVID-19 in the TOGETHER trial.",
    cites: 15,
    citesPerYear: 15,
    slug: createSlug("Effect of spirulina on risk of hospitalization and death among high-risk patients with COVID-19"),
    tags: extractTags("Effect of spirulina on risk of hospitalization and death among high-risk patients with COVID-19", "Journal of Alternative and Complementary Medicine"),
  },
  {
    id: 43,
    title: "Matched vs nonmatched placebos in a platform trial: The TOGETHER randomized clinical trial experience",
    authors: "G Reis, EASM Silva, DCM Silva, LJ Thabane, AC Ferreira, VEG de Souza-Campos, APM Almeida, AM Nogueira, EDS Callegari, ADF de Figueiredo-Neto, JI Forrest, JH Park, CS Wiens, CM Guo, K Thorlund, EJ Mills",
    year: 2024,
    journal: "Clinical Trials",
    imageUrl: "/pdf/thumbnails/Reis-2024-Matched vs Nonmatched Placebos in a.png",
    aiHint: "clinical trials placebo design methodology TOGETHER",
    pdfUrl: "/pdf/Reis-2024-Matched vs Nonmatched Placebos in a.pdf",
    abstract: "Background: Platform trials testing multiple interventions raise questions about placebo matching. We examined the impact of matched versus nonmatched placebos on trial outcomes and participant blinding in the TOGETHER platform trial for COVID-19 treatments.",
    cites: 8,
    citesPerYear: 8,
    slug: createSlug("Matched vs nonmatched placebos in a platform trial: The TOGETHER randomized clinical trial experience"),
    tags: extractTags("Matched vs nonmatched placebos in a platform trial: The TOGETHER randomized clinical trial experience", "Clinical Trials"),
  },
  {
    id: 44,
    title: "Active case finding for HIV: a systematic review and meta-analysis",
    authors: "E Remera, JI Forrest, A Hladik, S Nsanzimana, A Binagwaho, EJ Mills",
    year: 2025,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Remera er al-2025-Acxtive case Finding.png",
    aiHint: "HIV active case finding systematic review meta-analysis",
    pdfUrl: "/pdf/Remera er al-2025-Acxtive case Finding.pdf",
    abstract: "Background: Active case finding strategies have been implemented to identify undiagnosed HIV cases. We conducted a systematic review and meta-analysis to evaluate the effectiveness of active case finding interventions for HIV testing and linkage to care.",
    cites: 5,
    citesPerYear: 5,
    slug: createSlug("Active case finding for HIV: a systematic review and meta-analysis"),
    tags: extractTags("Active case finding for HIV: a systematic review and meta-analysis", "The Lancet HIV"),
  },
  {
    id: 45,
    title: "Towards elimination of mother-to-child transmission of HIV in Rwanda: a nested case-control study",
    authors: "E Remera, JI Forrest, M Niyigena, F Ngabo, A Bukenya, A Binagwaho, EJ Mills, S Nsanzimana",
    year: 2021,
    journal: "BMC Public Health",
    imageUrl: "/pdf/thumbnails/Remera-2021-Towards elimination of mother-to-c.png",
    aiHint: "HIV mother-to-child transmission prevention Rwanda",
    pdfUrl: "/pdf/Remera-2021-Towards elimination of mother-to-c.pdf",
    abstract: "Background: Prevention of mother-to-child transmission (PMTCT) of HIV is critical for eliminating pediatric HIV. We conducted a nested case-control study to identify factors associated with mother-to-child HIV transmission in Rwanda.",
    cites: 24,
    citesPerYear: 6,
    slug: createSlug("Towards elimination of mother-to-child transmission of HIV in Rwanda"),
    tags: extractTags("Towards elimination of mother-to-child transmission of HIV in Rwanda", "BMC Public Health"),
  },
  {
    id: 46,
    title: "HIV testing and treatment outcomes among key populations in Rwanda: a systematic review",
    authors: "E Remera, JI Forrest, S Nsanzimana, A Binagwaho, EJ Mills",
    year: 2025,
    journal: "Journal of the International AIDS Society",
    imageUrl: "/pdf/thumbnails/Remera-2025-HIV.png",
    aiHint: "HIV key populations testing treatment Rwanda systematic review",
    pdfUrl: "/pdf/Remera-2025-HIV.pdf",
    abstract: "Background: Key populations face unique challenges in accessing HIV services. We systematically reviewed HIV testing and treatment outcomes among key populations in Rwanda to identify gaps and opportunities for improvement in service delivery.",
    cites: 2,
    citesPerYear: 2,
    slug: createSlug("HIV testing and treatment outcomes among key populations in Rwanda"),
    tags: extractTags("HIV testing and treatment outcomes among key populations in Rwanda", "Journal of the International AIDS Society"),
  },
  {
    id: 47,
    title: "Identifying self-perceived HIV-related stigma in a respondent-driven sample of men who have sex with men",
    authors: "D Tzemis, D Forrest, S Lampinen, J Hogg, J Forrest, TH Mathias, D Moore",
    year: 2013,
    journal: "AIDS Care",
    imageUrl: "/pdf/thumbnails/Tzemis-2013-Identifying self-perceived HIV-rel.png",
    aiHint: "HIV stigma MSM respondent-driven sampling",
    pdfUrl: "/pdf/Tzemis-2013-Identifying self-perceived HIV-rel.pdf",
    abstract: "Background: HIV-related stigma remains a significant barrier to HIV prevention and care among men who have sex with men (MSM). We used respondent-driven sampling to examine self-perceived HIV-related stigma among MSM in Vancouver, Canada.",
    cites: 56,
    citesPerYear: 4.67,
    slug: createSlug("Identifying self-perceived HIV-related stigma in a respondent-driven sample of men who have sex with men"),
    tags: extractTags("Identifying self-perceived HIV-related stigma in a respondent-driven sample of men who have sex with men", "AIDS Care"),
  },
  {
    id: 48,
    title: "Factors predictive of 30-day post-discharge mortality among HIV-positive patients admitted to hospital in British Columbia",
    authors: "V Wiseman, JI Forrest, H Nkala, N Lima, K Salters, C Cui, J Montaner, RS Hogg",
    year: 2012,
    journal: "International Journal of STD & AIDS",
    imageUrl: "/pdf/thumbnails/Wiseman-2012-Factors predictive of 30-day post.png",
    aiHint: "HIV hospitalization mortality British Columbia",
    pdfUrl: "/pdf/Wiseman-2012-Factors predictive of 30-day post.pdf",
    abstract: "Background: Post-discharge mortality among HIV-positive patients remains a concern. We examined factors predictive of 30-day post-discharge mortality among HIV-positive patients admitted to hospital in British Columbia, Canada.",
    cites: 41,
    citesPerYear: 3.15,
    slug: createSlug("Factors predictive of 30-day post-discharge mortality among HIV-positive patients admitted to hospital in British Columbia"),
    tags: extractTags("Factors predictive of 30-day post-discharge mortality among HIV-positive patients admitted to hospital in British Columbia", "International Journal of STD & AIDS"),
  },
];
